version: '3'
services:
  app:
    image: django-rest
    tty: true
    env_file:
      - dev.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./app:/app

  postgres:
    image: postgres:latest
    env_file:
      - dev.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
