name: base
dependencies:
  - python=3.6
  - psycopg2=2.7.4
  - pip:
    - coverage==4.3.4
    - django==2.2.3
    - djangorestframework==3.7.7
    - coreapi==2.3.3
    - django-cors-headers
    - drf_writable_nested==0.5.1
    - pillow==6.0.0
    - djangorestframework_simplejwt==4.3.0

