# Generated by Django 2.0.3 on 2019-07-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member_since',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
